<a href="https://colab.research.google.com/github/Naveen8056/MachineLearning_Projects/blob/main/Weather_prediction_using_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [ ]:
df=pd.read_csv('weatherAUS - weatherAUS.csv')
df.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  

[5 rows x 23 columns]

In [ ]:
df.isnull().sum()

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RainTomorrow      3267
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for col in df.columns:
    if df[col].dtype=='object':
        df[col]=le.fit_transform(df[col])


In [ ]:
for col in df:
    df[col]=df[col].fillna(df[col].mean())
df

Date  Location  MinTemp    MaxTemp  Rainfall  Evaporation  Sunshine  \
0        396         2     13.4  22.900000       0.6     5.468232  7.611178   
1        397         2      7.4  25.100000       0.0     5.468232  7.611178   
2        398         2     12.9  25.700000       0.0     5.468232  7.611178   
3        399         2      9.2  28.000000       0.0     5.468232  7.611178   
4        400         2     17.5  32.300000       1.0     5.468232  7.611178   
...      ...       ...      ...        ...       ...          ...       ...   
145455  3431        41      2.8  23.400000       0.0     5.468232  7.611178   
145456  3432        41      3.6  25.300000       0.0     5.468232  7.611178   
145457  3433        41      5.4  26.900000       0.0     5.468232  7.611178   
145458  3434        41      7.8  27.000000       0.0     5.468232  7.611178   
145459  3435        41     14.9  23.221348       0.0     5.468232  7.611178   

        WindGustDir  WindGustSpeed  WindDir9am  ...  Humidity9am  Humidity3pm  \
0                13       44.00000          13  ...         71.0         22.0   
1                14       44.00000           6  ...         44.0         25.0   
2                15       46.00000          13  ...         38.0         30.0   
3                 4       24.00000           9  ...         45.0         16.0   
4                13       41.00000           1  ...         82.0         33.0   
...             ...            ...         ...  ...          ...          ...   
145455            0       31.00000           9  ...         51.0         24.0   
145456            6       22.00000           9  ...         56.0         21.0   
145457            3       37.00000           9  ...         53.0         24.0   
145458            9       28.00000          10  ...         51.0         24.0   
145459           16       40.03523           2  ...         62.0         36.0   

        Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
0            1007.7       1007.1  8.000000   4.50993     16.9     21.8   
1            1010.6       1007.8  4.447461   4.50993     17.2     24.3   
2            1007.6       1008.7  4.447461   2.00000     21.0     23.2   
3            1017.6       1012.8  4.447461   4.50993     18.1     26.5   
4            1010.8       1006.0  7.000000   8.00000     17.8     29.7   
...             ...          ...       ...       ...      ...      ...   
145455       1024.6       1020.3  4.447461   4.50993     10.1     22.4   
145456       1023.5       1019.1  4.447461   4.50993     10.9     24.5   
145457       1021.0       1016.8  4.447461   4.50993     12.5     26.1   
145458       1019.4       1016.5  3.000000   2.00000     15.1     26.0   
145459       1020.2       1017.9  8.000000   8.00000     15.0     20.9   

        RainToday  RainTomorrow  
0               0             0  
1               0             0  
2               0             0  
3               0             0  
4               0             0  
...           ...           ...  
145455          0             0  
145456          0             0  
145457          0             0  
145458          0             0  
145459          0             2  

[145460 rows x 23 columns]

In [ ]:
df.isnull().sum()

Date             0
Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RainTomorrow     0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x = df.drop('RainTomorrow',axis=1)
y = df['RainTomorrow']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.svm import SVC
model = SVC(kernel='rbf')

In [ ]:
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
accuracy_score = accuracy_score(y_test,y_pred)
print(accuracy_score)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.7944452083046886
              precision    recall  f1-score   support

           0       0.79      0.99      0.88     22082
           1       0.84      0.19      0.32      6366
           2       0.00      0.00      0.00       644

    accuracy                           0.79     29092
   macro avg       0.54      0.40      0.40     29092
weighted avg       0.78      0.79      0.74     29092

[[21872   210     0]
 [ 5126  1240     0]
 [  610    34     0]]
